# Generated by Django 5.0.2 on 2024-03-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_remove_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catigary',
            new_name='catigory',
        ),
    ]
